"""add reset control to goal block items

Revision ID: 04772e368af9
Revises: a7a8fd33e3a4
Create Date: 2026-06-07 23:38:26.806639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04772e368af9'
down_revision = 'a7a8fd33e3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_reinicializacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.drop_column('ultima_reinicializacao')

    # ### end Alembic commands ###
