"""add cover image to goals

Revision ID: 1d3f65cd6c36
Revises: 8a1b1a4fe60a
Create Date: 2026-06-03 21:26:09.884675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3f65cd6c36'
down_revision = '8a1b1a4fe60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
