"""add streak fields to goal block items

Revision ID: 4a88127657ae
Revises: a73b81618ba0
Create Date: 2026-06-07 20:21:32.801524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a88127657ae'
down_revision = 'a73b81618ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_atual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('melhor_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ultima_data_streak', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.drop_column('ultima_data_streak')
        batch_op.drop_column('melhor_streak')
        batch_op.drop_column('streak_atual')

    # ### end Alembic commands ###
