"""update goal block items structure

Revision ID: 56764f48187f
Revises: 5be36da2b2c8
Create Date: 2026-06-02 12:34:34.392403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56764f48187f'
down_revision = '5be36da2b2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('conteudo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_item', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('arquivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.drop_column('arquivo')
        batch_op.drop_column('valor')
        batch_op.drop_column('data_item')
        batch_op.drop_column('conteudo')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
