"""update blocks and create block items

Revision ID: 5be36da2b2c8
Revises: c912d71eac4e
Create Date: 2026-06-02 11:17:15.144620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be36da2b2c8'
down_revision = 'c912d71eac4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_block_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['goal_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_block_items')
    # ### end Alembic commands ###
