"""add achievement xp rarity unlock date

Revision ID: 65855a31e51b
Revises: 1d3f65cd6c36
Create Date: 2026-06-06 00:22:40.568498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65855a31e51b'
down_revision = '1d3f65cd6c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('data_desbloqueio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('raridade', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('data_desbloqueio', sa.DateTime(), nullable=True))

    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.alter_column('subtipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.alter_column('subtipo',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('data_desbloqueio')
        batch_op.drop_column('raridade')
        batch_op.drop_column('xp')

    op.drop_table('user_achievements')
    # ### end Alembic commands ###
