"""create achievement definitions

Revision ID: 8e87a59f70f5
Revises: 65855a31e51b
Create Date: 2026-06-06 01:15:21.802643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e87a59f70f5'
down_revision = '65855a31e51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('raridade', sa.String(length=30), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('tarefas_requeridas', sa.Integer(), nullable=True),
    sa.Column('jornadas_requeridas', sa.Integer(), nullable=True),
    sa.Column('dias_consistencia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement_definitions')
    # ### end Alembic commands ###
