"""add recurrence fields to goal block items

Revision ID: 9e163737acef
Revises: da4dc3758f77
Create Date: 2026-06-06 12:15:06.128753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e163737acef'
down_revision = 'da4dc3758f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('meta_valor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_atual', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.drop_column('valor_atual')
        batch_op.drop_column('meta_valor')
        batch_op.drop_column('frequencia')

    # ### end Alembic commands ###
