"""add user streak fields

Revision ID: a30ce6ee37dd
Revises: 06f8dc5c11c1
Create Date: 2026-06-08 15:00:52.639948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30ce6ee37dd'
down_revision = '06f8dc5c11c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_atual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('melhor_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ultima_atividade', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ultima_atividade')
        batch_op.drop_column('melhor_streak')
        batch_op.drop_column('streak_atual')

    # ### end Alembic commands ###
