"""add last activity to goal block items

Revision ID: a73b81618ba0
Revises: 9e163737acef
Create Date: 2026-06-07 19:40:50.140409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73b81618ba0'
down_revision = '9e163737acef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_atividade', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_block_items', schema=None) as batch_op:
        batch_op.drop_column('ultima_atividade')

    # ### end Alembic commands ###
