"""update workspace blocks

Revision ID: c912d71eac4e
Revises: be398e4edecd
Create Date: 2026-06-02 11:09:14.431272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c912d71eac4e'
down_revision = 'be398e4edecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.drop_column('conteudo')
        batch_op.drop_column('concluido')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('concluido', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('conteudo', mysql.TEXT(), nullable=True))
        batch_op.drop_column('descricao')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
